#!/usr/local/bin/perl

# Convert Dictionary file to header file
# Usage: dict2c tdict.txt > tdict.h
# By: vuthi@ctrl.titech.ac.jp

print <<ENDEND;
/* This file is machine-generated by a perl script. */
/* Don't modify unless you maintain the word order. */

unsigned char *wordptr[]={
ENDEND
$c = 0;
while(<>) {
  chop;
  next if /^\s*$/;
  $i = length($_);
  $ex[$i]=1;
  $maxl = $i if $i > $maxl;
  print ",\n" if $c;
  printf "\"\\x%02X%s\"", $i, $_;
  $c++;
}

print <<ENDEND;
};
int numword = $c;
int maxwordlength = $maxl;
ENDEND
